### ISSUE TITLE
trouble compiling code

### ISSUE THREAD

**Issue by amityandersen** [RDarkins/lammps-hrex#2]
Hello,

Thank you for making your code available!

I was trying to compile your code with the 15Sep2022 version of LAMMPS, gcc version 10.2.0, and openmpi version 4.1.4. I ran into the following error:

../hrex.cpp:332:34: error: cannot bind rvalue reference of type 'std::vector<double>&&' to lvalue of type 'std::vector<double>'
  332 |     (*it)->root_unpack_potential(partner_packed_pot);

I changed line 332 in hrex.cpp to:

(*it)->root_unpack_potential(std::move(std::vector<double>(partner_packed_pot)));

to fix the problem, and it seems to be running well. BTW, what is the correct way of analyzing the hills and swap data it produces (some scripts for this would be great, but I could modify my own for REMD and metadynamics if given some pointers). 

Many thanks,
Amity

**Comment by RDarkins** [comment]
Hi Amity,

Thank you very much for raising this issue. I have applied your correction.

I will try to provide some example scripts for analysing the output files as soon as possible.

Robert
